[package]
name = "pos-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.15", features = ["csr"] }
leptos_router = { version = "0.8.11" }
leptos_meta = { version = "0.8.5" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.19.0", features = ["serde", "v4", "js"] }
chrono = { version = "0.4.43", features = ["serde", "wasmbind"] }
gloo-net = "0.6.0"
wasm-bindgen = "0.2.108"
web-sys = "0.3.85"
console_error_panic_hook = "0.1.7"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1